---
title: 'Add an image source'
output: rmarkdown::html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/"
)
```


## Adding an image source

There are two ways to add an image source to your map:

### The add_image() function

Using the `add_image()` function, you can add an image source by passing the image URL or file path directly to the `url` argument.

You can pass either a `map`or `mapProxy` object to `add_image()`.

```{r add-source-map}
library(toro)
library(sf)

epi_location <- data.frame(
  lon = 174.82103783265418,
  lat = -41.30961916092329
) |>
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

map() |>
  add_image(
    image_id = "epi_logo",
    image_url = "https://raw.githubusercontent.com/Epi-interactive-Ltd/toro/refs/heads/dev/vignettes/images/epi-logo.png"
  ) |>
  add_symbol_layer(
    id = "epi",
    source = epi_location,
    layout = get_layout_options(
      "symbol",
      list(
        icon_image = "epi_logo",
        icon_size = 0.1
      )
    )
  ) |>
  set_bounds(epi_location, max_zoom = 13)
```
