---
title: 'Add a text layer'
output: rmarkdown::html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/"
)
```

## Adding text layers

First, set up the base map with our data.

```{r base-map}
library(toro)
library(sf)

base_map <- map() |>
  add_feature_server_source(
    "https://services8.arcgis.com/AYGZtmUtpARUKBlB/arcgis/rest/services/Te_Reo_M%C4%81ori_Place_Names/FeatureServer/0/query?where=1=1&outFields=*&f=geojson",
    "maori_places_data",
    append_query_url = ""
  )
```

### Basic example

```{r basic-text, results='asis'}
base_map |>
  add_text_layer(
    id = "places_text",
    source = "maori_places_data",
    hover_column = "name",
    layout = toro::get_layout_options(
      "text",
      options = list(
        text_field = toro::get_column("name_mi")
      )
    )
  )
```

### Advanced example

```{r advanced-text, results='asis'}
base_map |>
  add_text_layer(
    id = "places_texts",
    source = "maori_places_data",
    hover_column = "name",
    layout = get_layout_options(
      "text",
      options = list(
        text_field = toro::get_column("name_mi"),
        text_size = get_column_group("type", c("river" = 18), 12),
        "symbol-sort-key" = get_column_group(
          "type",
          c(
            "city" = 6,
            "town" = 5,
            "village" = 4,
            "suburb" = 3,
            "locality" = 2
          ),
          1
        )
      )
    ),
    paint = get_paint_options(
      "text",
      options = list(
        colour = get_column_group(
          "type",
          c(
            "city" = "#014f86",
            "town" = "#0177CB",
            "village" = "#0195FE",
            "suburb" = "#34AAFE",
            "locality" = "#67BFFE"
          ),
          "#9AD4FE"
        )
      )
    )
  )
```
