---
title: 'Add a symbol layer'
output: rmarkdown::html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Adding symbol layers

First, set up the base map with our data.

```{r base-map}
library(toro)
library(sf)

base_map <- map(
  imageSources = list(
    list(
      id = "map_pin",
      url = "https://upload.wikimedia.org/wikipedia/commons/f/f2/678111-map-marker-512.png"
    )
  )
) |>
  add_feature_server_source(
    "https://services8.arcgis.com/AYGZtmUtpARUKBlB/arcgis/rest/services/Te_Reo_M%C4%81ori_Place_Names/FeatureServer/0/query?where=1=1&outFields=*&f=geojson",
    "maori_places_data",
    append_query_url = FALSE
  )
```

### Basic example

```{r basic-symbol, results='asis'}
base_map |>
  add_symbol_layer(
    id = "places_text",
    source = "maori_places_data",
    hover_column = "type",
    popup_column = "name",
    can_cluster = TRUE,
    filter = get_layer_filter("type == village"),
    layout = toro::get_layout_options(
      "symbol",
      options = list(
        icon_image = "map_pin",
        icon_size = 0.05
      )
    )
  )
```

### Advanced example

```{r advanced-symbol, results='asis'}
base_map |>
  add_symbol_layer(
    id = "awa_symbols",
    source = "maori_awa_data",
    hover_column = "name_mi",
    popup_column = "name",
    paint = get_paint_options(
      "symbol",
      options = list(
        colour = get_column_group(
          "type",
          c("river" = "#014f86", "stream" = "#61a5c2"),
          "#a9d6e5"
        ),
        symbol_width = get_column_group("type", c("river" = 3), 1)
      )
    )
  )
```
